if("undefined"===typeof kotlin)throw Error("Error loading module 'promo'. Its dependency 'kotlin' was not found. Please, check whether 'kotlin' is loaded prior to 'promo'.");
var promo=function(G,e){function f(a){this.isEmpty=!1;this.positive=!0;this.elements=y();a=bb(e.isCharSequence(a)?a:z()).toString();if(r(a,"")||r(a,"-"))this.isEmpty=!0;switch(a.charCodeAt(0)){case 45:this.positive=!1;a=X(a,1);break;case 43:this.positive=!0,a=X(a,1)}this.elements.add_11rb$(!1);if(!r(a,"0"))for(a=cb(a);a.hasNext();){var b=va(a.next());var c=da(String.fromCharCode(b));b=t(0);b.elements=I([!0,!1,!0,!1]);var d=t(0);if(null==c){this.isEmpty=!0;break}else{switch(c){case 0:c=I([!1]);
break;case 1:c=I([!0]);break;case 2:c=I([!0,!1]);break;case 3:c=I([!0,!0]);break;case 4:c=I([!0,!1,!1]);break;case 5:c=I([!0,!1,!0]);break;case 6:c=I([!0,!0,!1]);break;case 7:c=I([!0,!0,!0]);break;case 8:c=I([!0,!1,!1,!1]);break;case 9:c=I([!0,!1,!1,!0]);break;default:throw Gb();}d.elements=c;c=U(this).abs();c=c.times_j8uhfx$(b).plus_j8uhfx$(d);this.elements=c.elements}}this.isEmpty&&(this.positive=!0,this.elements=I([!1]))}function t(a,b){b=b||Object.create(f.prototype);f.call(b,a.toString());return b}
function U(a,b){b=b||Object.create(f.prototype);t(0,b);b.isEmpty=a.isEmpty;b.elements=p(a.elements);b.positive=a.positive;return b}function wa(a){Na();this.prog_0=null;this.running_0=this.xMode=!1;var b=db();b.read_data_61zpoe$(a);this.prog_0=b;this.xMode=Y(this.prog_0.xMode);this.running_0=!1}function Oa(){Pa=this}function Na(){null===Pa&&new Oa;return Pa}function x(a,b){this.name_2w9maf$_0="add";this.list=a;this.leftBy=b}function xa(a,b){b=b||Object.create(x.prototype);x.call(b,I([a]),0);return b}
function L(a,b,c){this.name_4k6r51$_0="add_products";this.list=a;this.leftBy=c;this.div=b}function M(){Qa=this}function Q(a,b){V.call(this);this.name$=a;this.ordinal$=b}function ea(){ea=function(){};eb=new Q("Plus",0);fb=new Q("Minus",1);gb=new Q("Left",2);hb=new Q("Right",3);ib=new Q("CallIf",4);jb=new Q("DynamicCallIf",5)}function Ra(){ea();return eb}function Sa(){ea();return fb}function Ta(){ea();return gb}function Ua(){ea();return hb}function ya(){ea();return ib}function na(){ea();return jb}function kb(){null===
Qa&&new M;return Qa}function n(){}function w(a,b){this.name_ix49fx$_0="call_if";this.dynamic=b;this.value=a}function Z(){}function K(){this.name_olt8v1$_0="forever"}function E(a){za();this.name_azzy6j$_0="procedure";this.functionNumber=a;this.body_atn6ok$_0=y();this.level_f1c4jq$_0=2}function lb(){Va=this;this.mainFunName="main"}function za(){null===Va&&new lb;return Va}function P(a,b){V.call(this);this.name$=a;this.ordinal$=b}function Aa(){Aa=function(){};mb=new P("NotZero",0);nb=new P("Positive",
1);ob=new P("Negative",2)}function fa(){Aa();return mb}function ja(){Aa();return nb}function ka(){Aa();return ob}function B(a,b){this.name_6g6f01$_0="if";this.body_69tni2$_0=y();this.level_e1jj70$_0=a;this.pos=b}function Ba(a,b){b=b||Object.create(B.prototype);B.call(b,a,fa());return b}function aa(a,b,c){var d=u(A(a,10)),h;for(h=a.iterator();h.hasNext();){var e=h.next(),k=d.add_11rb$,g=y();for(e=e.iterator();e.hasNext();){var q=e.next();0<q.second&&g.add_11rb$(q)}e=u(A(g,10));for(g=g.iterator();g.hasNext();)q=
g.next(),e.add_11rb$(q.first);k.call(d,p(e))}this.list_0=p(d);this.complete_list_0=a;this.n_0=c;this.size_0=p(b);this.inlines_1c7vt9$_0=this.inline_0(0,y())}function pb(){return null==Ca?ha("input"):Ca}function Da(){return null==Ea?ha("output"):Ea}function oa(){return null==Fa?ha("runButton"):Fa}function pa(){return null==Ga?ha("stopButton"):Ga}function qa(){return null==Ha?ha("inputx"):Ha}function qb(){return null==Ia?ha("output_result"):Ia}function ra(){return null==Ja?ha("worker"):Ja}function rb(){var a,
b,c,d,h,l;Ca=e.isType(a=document.getElementById("input"),HTMLTextAreaElement)?a:z();Ea=e.isType(b=document.getElementById("output"),HTMLTextAreaElement)?b:z();Fa=e.isType(c=document.getElementById("run"),HTMLButtonElement)?c:z();Ga=e.isType(d=document.getElementById("stop"),HTMLButtonElement)?d:z();Ha=e.isType(h=document.getElementById("x"),HTMLInputElement)?h:z();Ia=e.isType(l=document.getElementById("result"),HTMLInputElement)?l:z();Ka=!0}function Hb(a){var b;qb().value="string"===typeof(b=a.data)?
b:z();ra().terminate();W=!1;oa().disabled=!1;pa().disabled=!0}function D(a){this.name_lp44vx$_0="move";this.value=a}function H(a){this.name_6zvap2$_0="program";this.programBody=y();this.xMode=a;this.level_2wvrcv$_0=1}function db(a){a=a||Object.create(H.prototype);H.call(a,!1);return a}function R(a,b){V.call(this);this.name$=a;this.ordinal$=b}function Wa(){Wa=function(){};sb=new R("For",0);tb=new R("While",1)}function la(){Wa();return sb}function ia(){Wa();return tb}function F(a,b){this.name_jktdu5$_0=
"loop";this.body_jr65c4$_0=y();this.level_vgzaj6$_0=a;this.loop=b}function N(a,b){this.program_0=a;this.i_0=0;this.list_0=ub();this.input_0=b;this.level_0=1;this.nOnLevel_0=ub();this.result=this.run_0()}var da=e.kotlin.text.toIntOrNull_pdl1vz$,z=e.throwCCE,ba=e.kotlin.collections.listOf_mh5how$,O=e.kotlin.collections.plus_mydzjv$,p=e.kotlin.collections.toMutableList_4c7yge$,I=e.kotlin.collections.mutableListOf_i5x0yv$,Ib=e.kotlin.collections.reversed_7wnvza$,Jb=e.kotlin.ArithmeticException_init,Xa=
e.hashCode,r=e.equals,X=e.kotlin.text.drop_6ic1pp$,cb=e.kotlin.text.iterator_gw00vp$,Gb=e.kotlin.Exception_init,va=e.unboxChar,J=e.Kind.CLASS,y=e.kotlin.collections.ArrayList_init_287e2$,bb=e.kotlin.text.trim_gw00vp$,vb=Math,u=e.kotlin.collections.ArrayList_init_ww73n8$,Kb=e.kotlin.Unit,Ya=e.Kind.OBJECT,Y=e.ensureNotNull,S=e.kotlin.text.split_ip8yn$,m=e.kotlin.Exception_init_pdl1vj$,ma=e.kotlin.collections.drop_ba2ldo$,T=e.kotlin.text.dropLast_6ic1pp$,La=e.kotlin.text.toInt_pdl1vz$,Lb=e.toString,
V=e.kotlin.Enum,Za=e.throwISE,wb=e.kotlin.text.contains_sgbm27$,Mb=e.kotlin.text.take_6ic1pp$,ca=e.kotlin.text.replace_680rmw$,Nb=e.kotlin.text.toInt_6ic1pp$,sa=e.kotlin.collections.last_2p1efm$,$a=e.kotlin.Pair,xb=e.kotlin.collections.reverse_vvxzk3$,yb=e.kotlin.collections.first_2p1efm$,Ma=e.kotlin.collections.dropLast_yzln2o$,Ob=e.kotlin.text.StringBuilder_init,ab=e.toBoxedChar,A=e.kotlin.collections.collectionSizeOrDefault_ba2ldo$,ta=e.kotlin.collections.checkIndexOverflow_za3lpa$,Pb=e.kotlin.collections.zip_45mdf7$,
zb=e.kotlin.text.last_gw00vp$,Qb=e.kotlin.collections.listOf_i5x0yv$,Ab=e.Kind.INTERFACE,Rb=e.kotlin.text.get_indices_gw00vp$,Bb=e.kotlin.collections.lastOrNull_2p1efm$,Cb=e.kotlin.collections.toList_7wnvza$,ha=e.throwUPAE,Db=e.toChar,Eb=e.kotlin.collections.MutableList,Sb=e.kotlin.text.Regex_init_61zpoe$,ub=e.kotlin.collections.LinkedHashMap_init_q3lmfv$;Q.prototype=Object.create(V.prototype);Q.prototype.constructor=Q;P.prototype=Object.create(V.prototype);P.prototype.constructor=P;R.prototype=Object.create(V.prototype);
R.prototype.constructor=R;f.prototype.toIntOrNull=function(){return da(this.toString())};f.prototype.plus_za3lpa$=function(a){return this.plus_j8uhfx$(t(a))};f.prototype.divides_za3lpa$=function(a){return this.divides_j8uhfx$(t(a))};f.prototype.divides_j8uhfx$=function(a){var b;return null!=(b=this.div_j8uhfx$(a).times_j8uhfx$(a))?b.equals(this):null};f.prototype.div_za3lpa$=function(a){return this.div_j8uhfx$(t(a))};f.prototype.compareTo_za3lpa$=function(a){return this.compareTo_j8uhfx$(t(a))};f.prototype.times_za3lpa$=
function(a){return this.times_j8uhfx$(t(a))};f.prototype.isZero_0=function(a){return 1===a.elements.size&&!a.elements.get_za3lpa$(0)};f.prototype.equals=function(a){return this.isZero_0(this.minus_j8uhfx$(e.isType(a,f)?a:z()))};f.prototype.minus_j8uhfx$=function(a){a=U(a);a.positive=!a.positive;return this.plus_j8uhfx$(a)};f.prototype.abs=function(){var a=U(this);a.positive=!0;return a};f.prototype.compareTo_j8uhfx$=function(a){return null!=this&&this.equals(a)?0:this.minus_j8uhfx$(a).positive?1:
-1};f.prototype.Base10Add1_0=function(a){a=p(O(ba(0),a));var b=a.size-1|0;a.set_wxm5ur$(b,a.get_za3lpa$(b)+1|0);for(b=a.size-1|0;0<=b;b--)9<a.get_za3lpa$(b)&&(a.set_wxm5ur$(b-1|0,a.get_za3lpa$(b-1|0)+1|0),a.set_wxm5ur$(b,a.get_za3lpa$(b)-10|0));b=!1;var c=y();for(a=a.iterator();a.hasNext();){var d=a.next();b?c.add_11rb$(d):0!==d&&(c.add_11rb$(d),b=!0)}a=p(c);0===a.size&&a.add_11rb$(0);return a};f.prototype.Base10Multiply2_0=function(a){a=p(O(ba(0),a));for(var b=!1,c=a.size-1|0;0<=c;c--)a.set_wxm5ur$(c,
2*a.get_za3lpa$(c)|0),b&&a.set_wxm5ur$(c,a.get_za3lpa$(c)+1|0),b=!1,9<a.get_za3lpa$(c)&&(b=!0,a.set_wxm5ur$(c,a.get_za3lpa$(c)-10|0));b=!1;c=y();for(a=a.iterator();a.hasNext();){var d=a.next();b?c.add_11rb$(d):0!==d&&(c.add_11rb$(d),b=!0)}a=p(c);0===a.size&&a.add_11rb$(0);return a};f.prototype.toString=function(){var a;if(this.isEmpty)return"NaN";var b=I([0]);for(a=this.elements.iterator();a.hasNext();){var c=a.next();b=this.Base10Multiply2_0(b);c&&(b=this.Base10Add1_0(b))}a=this.positive?"":"-";
for(b=b.iterator();b.hasNext();)c=b.next(),a+=c.toString();return a};f.prototype.remove_leading_zeroes_0=function(a){var b=a.elements,c=!1,d=y();for(b=b.iterator();b.hasNext();){var h=b.next();c?d.add_11rb$(h):h&&(d.add_11rb$(h),c=!0)}a.elements=p(d);0===a.elements.size&&a.elements.add_11rb$(!1)};f.prototype.plus_j8uhfx$=function(a){if(this.positive||a.positive){if(!this.positive&&a.positive)return a.plus_j8uhfx$(this);if(a.positive){var b=U(this);a=U(a);for(var c=vb.max(b.elements.size,a.elements.size)+
1|0,d=!1,h=c-b.elements.size|0,e=u(h),k=0;k<h;k++)e.add_11rb$(!1);b.elements=p(O(e,b.elements));c=c-a.elements.size|0;h=u(c);for(e=0;e<c;e++)h.add_11rb$(!1);a.elements=p(O(h,a.elements));for(c=b.elements.size-1|0;0<=c;c--)h=b.elements.get_za3lpa$(c),e=a.elements.get_za3lpa$(c),d?(b.elements.set_wxm5ur$(c,!(h^e)),d=h|e):(b.elements.set_wxm5ur$(c,h^e),d=h&e);this.remove_leading_zeroes_0(b);return b}b=U(this).abs();a=U(a).abs();d=!0;e=vb.max(b.elements.size,a.elements.size);if(b.elements.size>a.elements.size)d=
!0;else if(b.elements.size<a.elements.size)d=!1;else for(c=0;c<e&&(!b.elements.get_za3lpa$(c)||a.elements.get_za3lpa$(c));c++)if(!b.elements.get_za3lpa$(c)&&a.elements.get_za3lpa$(c)){d=!1;break}d||(c=b,b=a,a=c);c=!1;h=a;e=e-a.elements.size|0;k=u(e);for(var g=0;g<e;g++)k.add_11rb$(!1);h.elements=p(O(k,a.elements));for(h=b.elements.size-1|0;0<=h;h--)e=b.elements.get_za3lpa$(h),k=a.elements.get_za3lpa$(h),c?(b.elements.set_wxm5ur$(h,!(e^k)),c=!e|k):(b.elements.set_wxm5ur$(h,e^k),c=!e&k);this.remove_leading_zeroes_0(b);
d||(b.positive=!1);return b}this.positive=!0;a.positive=!0;b=this.plus_j8uhfx$(a);b.positive=!1;return b};f.prototype.times_j8uhfx$=function(a){var b,c=t(0),d=U(this);if(this.isZero_0(a)||this.isZero_0(this))return t(0);if(this.elements.size<a.elements.size)return a.times_j8uhfx$(this);for(b=Ib(a.elements).iterator();b.hasNext();)b.next()&&(c=c.plus_j8uhfx$(d)),d.elements.add_11rb$(!1);c.positive=this.positive===a.positive;return c};f.prototype.div_j8uhfx$=function(a){var b=this.elements.size-a.elements.size+
1|0;var c=t(0);if(1>b)return c;c.positive=this.positive===a.positive;var d=this.abs();a=a.abs();if(null!=a&&a.equals(t(1)))return c.elements=this.elements,c;if(this.isZero_0(a))throw Jb();for(var e=u(b),l=0;l<b;l++)e.add_11rb$(!1);c.elements=p(e);b=c.elements.size;for(e=0;e<b;e++)c.elements.set_wxm5ur$(e,!0),0<c.times_j8uhfx$(a).compareTo_j8uhfx$(d)&&c.elements.set_wxm5ur$(e,!1);this.remove_leading_zeroes_0(c);return c};f.prototype.hashCode=function(){var a=Xa(this.isEmpty);a=(31*a|0)+Xa(this.positive)|
0;return a=(31*a|0)+Xa(this.elements)|0};f.$metadata$={kind:J,simpleName:"BigInt",interfaces:[]};Oa.prototype.toBBCL_61zpoe$=function(a){return kb().Promo2BBCL_y4putb$(a).show_data()};Oa.$metadata$={kind:Ya,simpleName:"Companion",interfaces:[]};var Pa=null;wa.prototype.run_samethread_j8uhfx$=function(a){return(new N(this.prog_0,a)).result};wa.$metadata$={kind:J,simpleName:"Promo",interfaces:[]};Object.defineProperty(x.prototype,"name",{get:function(){return this.name_2w9maf$_0}});x.prototype.show_data=
function(){var a=this.name+(0<this.leftBy?" "+this.leftBy:"")+" (",b,c="";for(b=this.list.iterator();b.hasNext();){var d=b.next();c=c+" "+d}return a+X(c,1)+")"};x.prototype.deep_copy=function(){return new x(this.list,this.leftBy)};x.prototype.is_equal_qxsc$=function(a){if(!e.isType(a,x))return!1;a=e.isType(a,x)?a:z();return r(a.list,this.list)&&a.leftBy===this.leftBy?!0:!1};x.prototype.read_data_61zpoe$=function(a){var b=p(S(a,[" "]));if(!r(b.get_za3lpa$(0),"("+this.name))throw m("Syntax Error");
if(40===b.get_za3lpa$(1).charCodeAt(0))this.leftBy=0,b=p(ma(b,1));else if(40===b.get_za3lpa$(2).charCodeAt(0)){a=da(b.get_za3lpa$(1));if(null==a)throw m("Syntax Error");this.leftBy=a;b=p(ma(b,2))}else throw m("Syntax Error");b.set_wxm5ur$(0,X(b.get_za3lpa$(0),1));b.set_wxm5ur$(b.size-1|0,T(b.get_za3lpa$(b.size-1|0),2));this.list=y();for(a=b.iterator();a.hasNext();)b=a.next(),this.list.add_11rb$(La(b))};x.$metadata$={kind:J,simpleName:"addCommand",interfaces:[Z]};Object.defineProperty(L.prototype,
"name",{get:function(){return this.name_4k6r51$_0}});L.prototype.show_data=function(){var a,b=this.name+" "+Lb(null!=(a=this.div)?a:"n")+(0<this.leftBy?" "+this.leftBy:"")+" (",c="";for(a=this.list.iterator();a.hasNext();){var d=a.next();c=c+" "+d}return b+X(c,1)+")"};L.prototype.deep_copy=function(){return new L(this.list,this.div,this.leftBy)};L.prototype.is_equal_qxsc$=function(a){if(!e.isType(a,L))return!1;a=e.isType(a,L)?a:z();return r(a.list,this.list)&&a.leftBy===this.leftBy&&a.div==this.div?
!0:!1};L.prototype.read_data_61zpoe$=function(a){a=p(S(a,[" "]));if(!r(a.get_za3lpa$(0),"("+this.name))throw m("Syntax Error");if(r(a.get_za3lpa$(1),"n"))this.div=null;else{var b=da(a.get_za3lpa$(1));if(null==b)throw m("Syntax Error");this.div=b}if(40===a.get_za3lpa$(2).charCodeAt(0))this.leftBy=0,a=p(ma(a,2));else if(40===a.get_za3lpa$(3).charCodeAt(0)){b=da(a.get_za3lpa$(2));if(null==b)throw m("Syntax Error");this.leftBy=b;a=p(ma(a,3))}else throw m("Syntax Error");a.set_wxm5ur$(0,X(a.get_za3lpa$(0),
1));a.set_wxm5ur$(a.size-1|0,T(a.get_za3lpa$(a.size-1|0),2));this.list=y();for(a=a.iterator();a.hasNext();)b=a.next(),this.list.add_11rb$(La(b))};L.$metadata$={kind:J,simpleName:"addProductsCommand",interfaces:[Z]};var eb,fb,gb,hb,ib,jb;Q.$metadata$={kind:J,simpleName:"command_names",interfaces:[V]};Q.values=function(){return[Ra(),Sa(),Ta(),Ua(),ya(),na()]};Q.valueOf_61zpoe$=function(a){switch(a){case "Plus":return Ra();case "Minus":return Sa();case "Left":return Ta();case "Right":return Ua();case "CallIf":return ya();
case "DynamicCallIf":return na();default:Za("No enum constant PromoCompiler.bbcompiler.command_names."+a)}};M.prototype.abs_kcn2v3$=function(a){return 0>a?-a|0:a};M.prototype.char2com_name_0=function(a){switch(a){case 43:return Ra();case 45:return Sa();case 62:return Ua();case 60:return Ta();case 35:return ya();case 64:return na();default:throw m("not a valid character");}};M.prototype.com_name2com_0=function(a,b){switch(a.name){case "Plus":return xa(b);case "Minus":return xa(-b|0);case "Right":return new D(b);
case "Left":return new D(-b|0);case "CallIf":return new w(b,!1);case "DynamicCallIf":return new w(-b|0,!0);default:throw m("not a valid command");}};M.prototype.valid_chars_0=function(a){switch(a.name){case "Plus":return"+";case "Minus":return"-";case "Right":return">";case "Left":return"<";case "CallIf":return"#@";case "DynamicCallIf":return"@";default:throw m("not a valid command");}};M.prototype.Promo2UnoptimizedBBCL_0=function(a){var b=Ob();var c=a.length;for(var d=0;d<c;d++){var e=a.charCodeAt(d);
wb("+-<>#@",va(ab(e)))&&b.append_s8itvh$(e)}a=b.toString();c=S(a,["+-"]);a=r(Mb(a,2),"><");a=new H(a);b=0;for(c=c.iterator();c.hasNext();){d=c.next();a.programBody.add_11rb$(new E(b));e=d+"!";for(var l,k=0;k<e.length&&33!==e.charCodeAt(k);){l=this.char2com_name_0(e.charCodeAt(k));for(var g=k,q=1;wb(this.valid_chars_0(l),e.charCodeAt(k+1|0));)k=k+1|0,q=q+1|0;k=k+1|0;l===ya()&&(g=d.substring(g,k),g=ca(ca(g,"#","1"),"@","0"),q=Nb(g,2));l===na()&&a.programBody.get_za3lpa$(b).body.add_11rb$(new D(q));
a.programBody.get_za3lpa$(b).body.add_11rb$(this.com_name2com_0(l,q));l===na()&&a.programBody.get_za3lpa$(b).body.add_11rb$(new D(-q|0))}b=b+1|0}return a};M.prototype.inline_0=function(a){var b=y();for(var c=sa(a.programBody).functionNumber,d=0,e=0;e<=c;e++)if(y(),!(a.programBody.get_za3lpa$(d).functionNumber>e)){var l=a.programBody.get_za3lpa$(d).get_calls_za3lpa$(c);if(null==l){var k=a.programBody;l=u(A(k,10));for(k=k.iterator();k.hasNext();){var g=k.next();l.add_11rb$(new $a(g.functionNumber,1))}b.add_11rb$(p(l))}else{g=
Y(l);l=u(A(g,10));var q;k=0;for(g=g.iterator();g.hasNext();){var m=g.next();l.add_11rb$(new $a(ta((q=k,k=q+1|0,q)),m))}b.add_11rb$(p(l))}d=d+1|0}e=a.programBody;d=u(A(e,10));for(e=e.iterator();e.hasNext();)q=e.next(),d.add_11rb$(q.body.size);for(b=(new aa(b,d,c)).inlines.iterator();b.hasNext();)c=b.next(),this.replace_0(a.programBody.get_za3lpa$(c.first),a.programBody.get_za3lpa$(c.second))};M.prototype.replace_0=function(a,b){if(e.isType(a,w)&&!a.dynamic&&a.value===b.functionNumber)b=b.deep_copy(),
a=Ba(3),a.body=b.body;else if(e.isType(a,n)){var c=a,d=a.body,h=u(A(d,10));for(d=d.iterator();d.hasNext();){var l=d.next();h.add_11rb$(this.replace_0(l,b))}c.body=p(h)}return a};M.prototype.combineAdds_0=function(a){var b=a.programBody,c=u(A(b,10));for(b=b.iterator();b.hasNext();){var d=b.next(),h=c.add_11rb$,l,k,g;if(0<d.body.size){var q=new E(d.functionNumber);var m=0,C=y(),f=y(),r=0;var t=d.body.size;for(var n=0;n<t;n++)if(e.isType(d.body.get_za3lpa$(n),x)&&1===(e.isType(l=d.body.get_za3lpa$(n),
x)?l:z()).list.size||e.isType(d.body.get_za3lpa$(n),D))if(e.isType(d.body.get_za3lpa$(n),x)){var v=(e.isType(k=d.body.get_za3lpa$(n),x)?k:z()).list.get_za3lpa$((e.isType(g=d.body.get_za3lpa$(n),x)?g:z()).leftBy),w=this.abs_kcn2v3$(m);if(0<m){for(;w>f.size;)f.add_11rb$(0);f.set_wxm5ur$(w-1|0,f.get_za3lpa$(w-1|0)+v|0)}else if(0>m){for(;w>C.size;)C.add_11rb$(0);C.set_wxm5ur$(w-1|0,C.get_za3lpa$(w-1|0)+v|0)}else 0===m&&(r=r+v|0)}else{var B;m=m+(e.isType(B=d.body.get_za3lpa$(n),D)?B:z()).value|0}else{if(0<
n&&(e.isType(d.body.get_za3lpa$(n-1|0),x)||e.isType(d.body.get_za3lpa$(n-1|0),D))){xb(C);f=O(O(C,I([r])),f);for(C=C.size;0===yb(f)&&0<C&&1!==f.size;)f=ma(f,1),C=C-1|0;for(;0===sa(f)&&(f.size-1|0)>C&&1!==f.size;)f=Ma(f,1);1===f.size&&0===f.get_za3lpa$(0)||q.body.add_11rb$(new x(p(f),C));0!==m&&q.body.add_11rb$(new D(m));m=0;C=y();f=y();r=0}q.body.add_11rb$(d.body.get_za3lpa$(n))}t=d.body.size-1|0;if(0<=t&&(e.isType(d.body.get_za3lpa$(t),x)||e.isType(d.body.get_za3lpa$(t),D))){xb(C);d=O(O(C,I([r])),
f);for(C=C.size;0===yb(d)&&0<C&&1!==d.size;)d=ma(d,1),C=C-1|0;for(;0===sa(d)&&(d.size-1|0)>C&&1!==d.size;)d=Ma(d,1);1===d.size&&0===d.get_za3lpa$(0)||q.body.add_11rb$(new x(p(d),C));0!==m&&q.body.add_11rb$(new D(m))}}else q=d;h.call(c,q)}a.programBody=p(c)};M.prototype.removeCallsToNothing_0=function(a){var b=a.programBody,c=u(A(b,10));for(b=b.iterator();b.hasNext();){var d=b.next();c.add_11rb$(d.functionNumber)}for(a=a.programBody.iterator();a.hasNext();){b=a.next();var h=b.body;d=y();for(h=h.iterator();h.hasNext();){var l=
h.next();(!e.isType(l,w)||l.dynamic||c.contains_11rb$(l.value))&&d.add_11rb$(l)}b.body=p(d)}};M.prototype.removeUseless_0=function(a){var b=a.get_calls_za3lpa$(sa(a.programBody).functionNumber);if(null!=b){var c=u(A(b,10));for(b=b.iterator();b.hasNext();){var d=b.next();c.add_11rb$(0<d)}b=-1;var e=a.programBody;d=y();for(e=e.iterator();e.hasNext();){var l=e.next();b=b+1|0;(c.get_za3lpa$(b)||0===b)&&d.add_11rb$(l)}a.programBody=p(d)}};M.prototype.optimize_simple_0=function(a){var b=a.programBody,c=
u(A(b,10));b=b.iterator();for(;b.hasNext();){var d=b.next(),h=c.add_11rb$,l=d,k=d.functionNumber,g=d.body,q;b:do{var f=0;for(q=g.iterator();q.hasNext();){var m=q.next();if(e.isType(m,w)&&m.value===k){q=f;break b}f=f+1|0}q=-1}while(0);g=q;if(-1===g)ua;else if(0===g)d=new E(d.functionNumber),d.body.add_11rb$(new K),l=d;else{g=new F(1,ia());l=new F(1,la());q=!1;for(f=d.body.iterator();f.hasNext();){m=f.next();var n=!1;!e.isType(m,w)||q||m.dynamic||m.value!==k||(n=q=!0);n||(q?l.body.add_11rb$(m):g.body.add_11rb$(m))}d=
new E(d.functionNumber);1===g.body.size&&e.isType(g.body.get_za3lpa$(0),x)?(g=g.body.get_za3lpa$(0),e.isType(g,x)&&(k=new L(g.list,this.abs_kcn2v3$(g.list.get_za3lpa$(g.leftBy)),g.leftBy),0<g.list.get_za3lpa$(g.leftBy)?(g=new B(1,ja()),g.body.add_11rb$(new K),d.body.add_11rb$(g)):0>g.list.get_za3lpa$(g.leftBy)?(g=new B(1,ka()),g.body.add_11rb$(new K),d.body.add_11rb$(g)):(g=Ba(1),g.body.add_11rb$(new K),d.body.add_11rb$(g)),d.body.add_11rb$(k))):d.body.add_11rb$(g);1===l.body.size&&e.isType(l.body.get_za3lpa$(0),
x)?(k=l.body.get_za3lpa$(0),e.isType(k,x)&&(k=new L(k.list,null,k.leftBy),d.body.add_11rb$(k))):l.body.isEmpty()||d.body.add_11rb$(l);l=d}h.call(c,l)}a.programBody=p(c)};M.prototype.Promo2BBCL_y4putb$=function(a){a=this.Promo2UnoptimizedBBCL_0(a);do{var b=a.deep_copy();this.removeCallsToNothing_0(a);this.inline_0(a);this.combineAdds_0(a);this.removeUseless_0(a);this.optimize_simple_0(a);a.deep_set_level_za3lpa$(1)}while(!a.is_equal_qxsc$(b));var c=a.programBody;b=y();for(c=c.iterator();c.hasNext();){var d=
c.next();(0<d.body.size||0===d.functionNumber)&&b.add_11rb$(d)}a.programBody=p(b);return a};M.$metadata$={kind:Ya,simpleName:"bbcompiler",interfaces:[]};var Qa=null;n.prototype.deep_set_level_za3lpa$=function(a){this.level=a;var b;for(b=this.body.iterator();b.hasNext();){var c=b.next();e.isType(c,n)&&c.deep_set_level_za3lpa$(a+1|0)}};n.prototype.get_calls_za3lpa$=function(a){var b=a+1|0;var c=u(b);for(var d=0;d<b;d++)c.add_11rb$(0);d=c;for(b=this.body.iterator();b.hasNext();){var h=b.next();if(e.isType(h,
w)){if(h.dynamic)return null;c=h.value;d.set_wxm5ur$(c,d.get_za3lpa$(c)+1|0)}if(e.isType(h,n)){if(null==h.get_calls_za3lpa$(a))return null;d=Pb(d,Y(h.get_calls_za3lpa$(a)));c=u(A(d,10));for(d=d.iterator();d.hasNext();)h=d.next(),c.add_11rb$(h.first+h.second|0);d=p(c)}}return d};n.prototype.read_body_61zpoe$=function(a){var b;if(40!==a.charCodeAt(0))throw m("Syntax error");if(41!==zb(a))throw m("Syntax error");if(2>a.length)throw m("Syntax error");a=b=T(X(a,1),1);a:do{var c=Rb(a);b=c.first;var d=c.last;
for(c=c.step;b<=d;b+=c)if(40===va(ab(a.charCodeAt(b)))){d=a.substring(b);break a}d=""}while(0);b=d;a=0;d="";this.body=y();for(b=cb(b);b.hasNext();){c=va(b.next());40===c&&(a=a+1|0);41===c&&(a=a-1|0);if(0>a)throw m("Syntax error");d+=String.fromCharCode(c);if(41===c&&0===a){var e=X(S(d,[" "]).get_za3lpa$(0),1);41===zb(e)&&(e=T(e,1));var l=null;for(c=Qb([xa(0),new L(y(),0,0),new w(0,!1),new K,new E(0),Ba(0),new D(0),new F(0,ia())]).iterator();c.hasNext();){var k=c.next();r(e,k.name)&&(l=k,k.read_data_61zpoe$(d),
this.body.add_11rb$(k))}if(null==l)throw m("Syntax error");d=""}}if(0<d.length)throw m("Syntax error");};n.$metadata$={kind:Ab,simpleName:"bodyInterface",interfaces:[Z]};Object.defineProperty(w.prototype,"name",{get:function(){return this.name_ix49fx$_0}});w.prototype.dynamic_names_0=function(a){return a?" dynamic":""};w.prototype.show_data=function(){return this.name+""+this.dynamic_names_0(this.dynamic)+" "+this.value.toString()};w.prototype.deep_copy=function(){return new w(this.value,this.dynamic)};
w.prototype.is_equal_qxsc$=function(a){if(!e.isType(a,w))return!1;a=e.isType(a,w)?a:z();return a.dynamic!==this.dynamic||a.value!==this.value?!1:!0};w.prototype.read_data_61zpoe$=function(a){a=S(a,[" "]);if(!r(a.get_za3lpa$(0),"("+this.name))throw m("Syntax Error");if(2===a.size)this.dynamic=!1,this.value=La(T(a.get_za3lpa$(1),1));else if(r(a.get_za3lpa$(1),"dynamic"))this.dynamic=!0,this.value=La(T(a.get_za3lpa$(2),1));else throw m("Syntax Error");};w.$metadata$={kind:J,simpleName:"callIfCommand",
interfaces:[Z]};Z.$metadata$={kind:Ab,simpleName:"commandInterface",interfaces:[]};Object.defineProperty(K.prototype,"name",{get:function(){return this.name_olt8v1$_0}});K.prototype.deep_copy=function(){return new K};K.prototype.show_data=function(){return this.name};K.prototype.is_equal_qxsc$=function(a){return e.isType(a,K)?!0:!1};K.prototype.read_data_61zpoe$=function(a){ua};K.$metadata$={kind:J,simpleName:"foreverCommand",interfaces:[Z]};Object.defineProperty(E.prototype,"name",{get:function(){return this.name_azzy6j$_0}});
lb.$metadata$={kind:Ya,simpleName:"Companion",interfaces:[]};var Va=null;Object.defineProperty(E.prototype,"body",{get:function(){return this.body_atn6ok$_0},set:function(a){this.body_atn6ok$_0=a}});Object.defineProperty(E.prototype,"level",{get:function(){return this.level_f1c4jq$_0},set:function(a){this.level_f1c4jq$_0=a}});E.prototype.show_data=function(){var a=this.name+" "+(0!==this.functionNumber?this.functionNumber.toString():za().mainFunName)+"\n",b=this.body,c=u(A(b,10));for(b=b.iterator();b.hasNext();){var d=
b.next();c.add_11rb$("("+d.show_data()+")\n")}b="";for(c=c.iterator();c.hasNext();)d=c.next(),b+=d;return a+=T(b,1)};E.prototype.deep_copy=function(){var a=new E(this.functionNumber);a.level=this.level;var b=this.body,c=u(A(b,10));for(b=b.iterator();b.hasNext();){var d=b.next();c.add_11rb$(d.deep_copy())}a.body=p(c);return a};E.prototype.is_equal_qxsc$=function(a){if(!e.isType(a,E))return!1;var b=e.isType(a,E)?a:z();if(b.level!==this.level||b.functionNumber!==this.functionNumber)return!1;var c=this.body;
a=u(A(c,10));var d,h=0;for(c=c.iterator();c.hasNext();){var l=c.next(),k=a.add_11rb$,g=ta((d=h,h=d+1|0,d));k.call(a,l.is_equal_qxsc$(b.body.get_za3lpa$(g)))}d=!0;for(a=a.iterator();a.hasNext();)b=a.next(),d=d&&b;return d?!0:!1};E.prototype.read_data_61zpoe$=function(a){var b=S(a,[" "]);if(!r(b.get_za3lpa$(0),"("+this.name))throw m("Syntax Error");if(r(b.get_za3lpa$(1),za().mainFunName))this.functionNumber=0;else{b=da(b.get_za3lpa$(1));if(null==b)throw m("Syntax Error");this.functionNumber=b}this.read_body_61zpoe$(a)};
E.$metadata$={kind:J,simpleName:"funCommand",interfaces:[n]};var mb,nb,ob;P.$metadata$={kind:J,simpleName:"If",interfaces:[V]};P.values=function(){return[fa(),ja(),ka()]};P.valueOf_61zpoe$=function(a){switch(a){case "NotZero":return fa();case "Positive":return ja();case "Negative":return ka();default:Za("No enum constant PromoCompiler.If."+a)}};Object.defineProperty(B.prototype,"name",{get:function(){return this.name_6g6f01$_0},set:function(a){this.name_6g6f01$_0=a}});Object.defineProperty(B.prototype,
"body",{get:function(){return this.body_69tni2$_0},set:function(a){this.body_69tni2$_0=a}});Object.defineProperty(B.prototype,"level",{get:function(){return this.level_e1jj70$_0},set:function(a){this.level_e1jj70$_0=a}});B.prototype.show_data=function(){var a=this.name;this.pos!==fa()&&(a+=" "+this.pos.name.toLowerCase());a+="\n";var b=this.body,c=u(A(b,10));for(b=b.iterator();b.hasNext();){var d=b.next();c.add_11rb$("("+d.show_data()+")\n")}b="";for(c=c.iterator();c.hasNext();)d=c.next(),b+=d;return a+=
T(b,1)};B.prototype.deep_copy=function(){var a=new B(this.level,this.pos),b=this.body,c=u(A(b,10));for(b=b.iterator();b.hasNext();){var d=b.next();c.add_11rb$(d.deep_copy())}a.body=p(c);return a};B.prototype.is_equal_qxsc$=function(a){if(!e.isType(a,B))return!1;var b=e.isType(a,B)?a:z();if(b.level!==this.level||b.pos!==this.pos)return!1;var c=this.body;a=u(A(c,10));var d,h=0;for(c=c.iterator();c.hasNext();){var l=c.next(),k=a.add_11rb$,g=ta((d=h,h=d+1|0,d));k.call(a,l.is_equal_qxsc$(b.body.get_za3lpa$(g)))}d=
!0;for(a=a.iterator();a.hasNext();)b=a.next(),d=d&&b;return d?!0:!1};B.prototype.read_data_61zpoe$=function(a){var b=S(a,[" "]);if(!r(b.get_za3lpa$(0),"("+this.name))throw m("Syntax Error");if(40===b.get_za3lpa$(1).charCodeAt(0))b=fa();else if(40===b.get_za3lpa$(2).charCodeAt(0))if(r(b.get_za3lpa$(1),"positive"))b=ja();else if(r(b.get_za3lpa$(1),"negative"))b=ka();else throw m("Syntax Error");else throw m("Syntax Error");this.pos=b;this.read_body_61zpoe$(a)};B.$metadata$={kind:J,simpleName:"ifCommand",
interfaces:[n]};Object.defineProperty(aa.prototype,"inlines",{get:function(){return this.inlines_1c7vt9$_0},set:function(a){this.inlines_1c7vt9$_0=a}});aa.prototype.nr_calls_0=function(a,b){var c=this.complete_list_0.get_za3lpa$(a),d;a:do{var e=0;for(d=c.iterator();d.hasNext();){if(d.next().first===b){d=e;break a}e=e+1|0}d=-1}while(0);b=d;return-1===b?0:this.complete_list_0.get_za3lpa$(a).get_za3lpa$(b).second};aa.prototype.get_cycles_0=function(a,b,c){var d=Bb(Ma(b,1)),e=sa(b);var l=a.get_za3lpa$(e);
var k=Ma(b,1);for(l=l.iterator();l.hasNext();){var g=l.next();if(null!=d)if(k.contains_11rb$(g)){c.set_wxm5ur$(e,!0);for(var f=b.size-1|0;b.get_za3lpa$(f)!==g;)c.set_wxm5ur$(b.get_za3lpa$(f),!0),f=f-1|0;c.set_wxm5ur$(b.get_za3lpa$(f),!0)}else c=this.get_cycles_0(a,O(b,ba(g)),c);else c=this.get_cycles_0(a,O(b,ba(e)),c)}return c};aa.prototype.inline_0=function(a,b){var c=y(),d=Bb(b);var h=this.list_0;var l=ba(0);for(var k=this.n_0+1|0,g=u(k),f=0;f<k;f++)g.add_11rb$(!1);h=this.get_cycles_0(h,l,g);for(l=
Cb(this.list_0.get_za3lpa$(a)).iterator();l.hasNext();)k=l.next(),this.list_0.get_za3lpa$(a).contains_11rb$(k)&&null!=d?b.contains_11rb$(k)||(c=this.inline_0(k,O(b,ba(a)))):c=this.inline_0(k,O(b,ba(a)));if(null!=d&&this.should_inline_0(d,a)){l=!0;k=Cb(this.list_0.get_za3lpa$(a));for(b=k.iterator();b.hasNext();){g=b.next();var m=this.list_0;f=u(A(m,10));for(m=m.iterator();m.hasNext();){var n=m.next();f.add_11rb$(p(n))}f=p(f);f.get_za3lpa$(d).remove_11rb$(a);f.get_za3lpa$(a).remove_11rb$(g);m=ba(0);
n=this.n_0+1|0;for(var r=u(n),t=0;t<n;t++)r.add_11rb$(!1);f=this.get_cycles_0(f,m,r);a!==g&&d!==g&&(!h.get_za3lpa$(a)||h.get_za3lpa$(d)&&h.get_za3lpa$(g)||f.get_za3lpa$(a))||(l=!1)}if(l){for(h=k.iterator();h.hasNext();)b=h.next(),this.list_0.get_za3lpa$(d).remove_11rb$(a),this.list_0.get_za3lpa$(a).remove_11rb$(b),this.list_0.get_za3lpa$(d).contains_11rb$(b)||this.list_0.get_za3lpa$(d).add_11rb$(b);this.size_0.set_wxm5ur$(d,this.size_0.get_za3lpa$(d)+e.imul(this.nr_calls_0(d,a),this.size_0.get_za3lpa$(a))|
0);c=p(O(c,I([new $a(d,a)])))}}return p(c)};aa.prototype.should_inline_0=function(a,b){return-1===a?!1:100>=(this.size_0.get_za3lpa$(a)+e.imul(this.nr_calls_0(a,b),this.size_0.get_za3lpa$(b))|0)};aa.$metadata$={kind:J,simpleName:"inliner",interfaces:[]};var W,Ca,Ea,Fa,Ga,Ha,Ia,Ja;Object.defineProperty(D.prototype,"name",{get:function(){return this.name_lp44vx$_0}});D.prototype.show_data=function(){return this.name+" "+this.value.toString()};D.prototype.deep_copy=function(){return new D(this.value)};
D.prototype.is_equal_qxsc$=function(a){return e.isType(a,D)&&(e.isType(a,D)?a:z()).value===this.value?!0:!1};D.prototype.read_data_61zpoe$=function(a){a=S(a,[" "]);if(!r(a.get_za3lpa$(0),"("+this.name))throw m("Syntax Error");a=da(T(a.get_za3lpa$(1),1));if(null==a)throw m("Syntax Error");this.value=a};D.$metadata$={kind:J,simpleName:"moveCommand",interfaces:[Z]};Object.defineProperty(H.prototype,"name",{get:function(){return this.name_6zvap2$_0}});Object.defineProperty(H.prototype,"body",{get:function(){var a;
return e.isType(a=this.programBody,Eb)?a:z()},set:function(a){this.programBody=e.isType(a,Eb)?a:z()}});Object.defineProperty(H.prototype,"level",{get:function(){return this.level_2wvrcv$_0},set:function(a){this.level_2wvrcv$_0=a}});H.prototype.show_data=function(){var a="("+this.name+" "+(Y(this.xMode)?"x":"i")+"\n",b=this.body,c=u(A(b,10));for(b=b.iterator();b.hasNext();){var d=b.next();c.add_11rb$("("+d.show_data()+")\n")}b="";for(c=c.iterator();c.hasNext();)d=c.next(),b+=d;a+=T(b,1);return a+")"};
H.prototype.deep_copy=function(){var a=new H(this.xMode);a.level=this.level;var b=this.body,c=u(A(b,10));for(b=b.iterator();b.hasNext();){var d=b.next();c.add_11rb$(d.deep_copy())}a.body=p(c);return a};H.prototype.is_equal_qxsc$=function(a){if(!e.isType(a,H))return!1;var b=e.isType(a,H)?a:z();if(b.level!==this.level||b.xMode!=this.xMode)return!1;var c=this.body;a=u(A(c,10));var d,h=0;for(c=c.iterator();c.hasNext();){var f=c.next(),k=a.add_11rb$,g=ta((d=h,h=d+1|0,d));k.call(a,f.is_equal_qxsc$(b.body.get_za3lpa$(g)))}d=
!0;for(a=a.iterator();a.hasNext();)b=a.next(),d=d&&b;return d?!0:!1};H.prototype.read_data_61zpoe$=function(a){a=ca(a,"\n"," ");a=Sb("\\s+").replace_x2uqeu$(a," ");a=ca(a,") (",")(");a=ca(a,") )","))");a=ca(a,"( (","((");var b=S(a,[" "]);if(!r(b.get_za3lpa$(0),"("+this.name))throw m("Syntax Error");if(r(b.get_za3lpa$(1),"x"))this.xMode=!0;else if(r(b.get_za3lpa$(1),"i"))this.xMode=!1;else throw m("Syntax Error");this.read_body_61zpoe$(a);this.deep_set_level_za3lpa$(1)};H.$metadata$={kind:J,simpleName:"programCommand",
interfaces:[n]};var sb,tb;R.$metadata$={kind:J,simpleName:"loop",interfaces:[V]};R.values=function(){return[la(),ia()]};R.valueOf_61zpoe$=function(a){switch(a){case "For":return la();case "While":return ia();default:Za("No enum constant PromoCompiler.loop."+a)}};Object.defineProperty(F.prototype,"name",{get:function(){return this.name_jktdu5$_0},set:function(a){this.name_jktdu5$_0=a}});Object.defineProperty(F.prototype,"body",{get:function(){return this.body_jr65c4$_0},set:function(a){this.body_jr65c4$_0=
a}});Object.defineProperty(F.prototype,"level",{get:function(){return this.level_vgzaj6$_0},set:function(a){this.level_vgzaj6$_0=a}});F.prototype.show_data=function(){var a=this.name+" "+this.loop.name.toLowerCase()+"\n",b=this.body,c=u(A(b,10));for(b=b.iterator();b.hasNext();){var d=b.next();c.add_11rb$("("+d.show_data()+")\n")}b="";for(c=c.iterator();c.hasNext();)d=c.next(),b+=d;return a+=T(b,1)};F.prototype.deep_copy=function(){var a=new F(this.level,this.loop),b=this.body,c=u(A(b,10));for(b=b.iterator();b.hasNext();){var d=
b.next();c.add_11rb$(d.deep_copy())}a.body=p(c);return a};F.prototype.is_equal_qxsc$=function(a){if(!e.isType(a,F))return!1;var b=e.isType(a,F)?a:z();if(b.level!==this.level||b.loop!==this.loop)return!1;var c=this.body;a=u(A(c,10));var d,h=0;for(c=c.iterator();c.hasNext();){var f=c.next(),k=a.add_11rb$,g=ta((d=h,h=d+1|0,d));k.call(a,f.is_equal_qxsc$(b.body.get_za3lpa$(g)))}d=!0;for(a=a.iterator();a.hasNext();)b=a.next(),d=d&&b;return d?!0:!1};F.prototype.read_data_61zpoe$=function(a){var b=S(a,[" "]);
if(!r(b.get_za3lpa$(0),"("+this.name))throw m("Syntax Error");if(r(b.get_za3lpa$(1),"for"))this.loop=la();else if(r(b.get_za3lpa$(1),"while"))this.loop=ia();else throw m("Syntax Error");this.read_body_61zpoe$(a)};F.$metadata$={kind:J,simpleName:"repeatCommand",interfaces:[n]};N.prototype.run_0=function(){if(this.input_0.isEmpty)return this.input_0;var a=this.list_0,b=Y(this.program_0.xMode)?this.input_0:t(0);a.put_xwzc9p$(0,b);this.runFunction_0(0);return this.CurrentPosition_0()};N.prototype.runFunction_0=
function(a){var b=this.program_0.programBody,c;a:do{var d=0;for(c=b.iterator();c.hasNext();){if(c.next().functionNumber===a){c=d;break a}d=d+1|0}c=-1}while(0);a=c;if(-1!==a){this.level_0=this.level_0+1|0;for(a=this.program_0.programBody.get_za3lpa$(a).body.iterator();a.hasNext();)b=a.next(),this.runCommand_0(b);this.level_0=this.level_0-1|0}};N.prototype.runCommand_0=function(a){if(e.isType(a,x))this.add_0(a);else if(e.isType(a,L))this.addProducts_0(a);else if(e.isType(a,w))this.callIf_0(a);else if(e.isType(a,
K))this.forever_0(a);else if(e.isType(a,B))this.runIf_0(a);else if(e.isType(a,D))this.move_0(a);else if(e.isType(a,F))this.runRepeat_0(a);else throw m("program formatted incorrectly");};N.prototype.runRepeat_0=function(a){var b;if(a.loop===ia()){var c=this.nOnLevel_0;var d=this.level_0,e=t(0);c.put_xwzc9p$(d,e);for(this.level_0=this.level_0+1|0;null==(b=this.CurrentPosition_0())||!b.equals(t(0));){for(c=a.body.iterator();c.hasNext();)d=c.next(),this.runCommand_0(d);c=this.nOnLevel_0;d=this.level_0-
1|0;e=Y(this.nOnLevel_0.get_11rb$(this.level_0-1|0)).plus_za3lpa$(1);c.put_xwzc9p$(d,e)}this.level_0=this.level_0-1|0}else if(a.loop===la()){b=this.nOnLevel_0;c=this.level_0;d=b.get_11rb$(c);null==d?(d=t(0),b.put_xwzc9p$(c,d),b=d):b=d;c=b;this.level_0=this.level_0+1|0;for(d=t(0);0>d.compareTo_j8uhfx$(c);){for(b=a.body.iterator();b.hasNext();)e=b.next(),this.runCommand_0(e);d=d.plus_za3lpa$(1)}this.level_0=this.level_0-1|0;a=this.nOnLevel_0;b=this.level_0;c=t(0);a.put_xwzc9p$(b,c)}};N.prototype.move_0=
function(a){this.i_0=this.i_0+a.value|0};N.prototype.runIf_0=function(a){var b;this.level_0=this.level_0+1|0;if((null==(b=this.CurrentPosition_0())||!b.equals(t(0)))&&a.pos===fa())for(a=a.body.iterator();a.hasNext();)b=a.next(),this.runCommand_0(b);else if(0<this.CurrentPosition_0().compareTo_za3lpa$(0)&&a.pos===ja())for(a=a.body.iterator();a.hasNext();)b=a.next(),this.runCommand_0(b);else if(0<this.CurrentPosition_0().compareTo_za3lpa$(0)&&a.pos===ka())for(a=a.body.iterator();a.hasNext();)b=a.next(),
this.runCommand_0(b);this.level_0=this.level_0-1|0};N.prototype.forever_0=function(a){for(;;)ua};N.prototype.callIf_0=function(a){var b,c;if(null==(b=this.CurrentPosition_0())||!b.equals(t(0)))if(a.dynamic){b=this.list_0;a=this.i_0+a.value|0;var d=b.get_11rb$(a);null==d?(d=t(0),b.put_xwzc9p$(a,d),b=d):b=d;this.runFunction_0(null!=(c=b.toIntOrNull())?c:-1)}else this.runFunction_0(a.value)};N.prototype.addProducts_0=function(a){if(null!=a.div)if(this.CurrentPosition_0().abs().divides_za3lpa$(Y(a.div))){var b=
this.CurrentPosition_0().abs().div_za3lpa$(Y(a.div)),c=this.i_0;this.i_0=this.i_0-a.leftBy|0;this.nOnLevel_0.put_xwzc9p$(this.level_0,b);for(a=a.list.iterator();a.hasNext();){var d=a.next(),e=this.list_0,f=this.i_0;d=this.CurrentPosition_0().plus_j8uhfx$(b.times_za3lpa$(d));e.put_xwzc9p$(f,d);this.i_0=this.i_0+1|0}this.i_0=c}else for(;;)ua;else{b=this.nOnLevel_0;c=this.level_0;e=b.get_11rb$(c);null==e?(e=t(0),b.put_xwzc9p$(c,e),b=e):b=e;c=this.i_0;this.i_0=this.i_0-a.leftBy|0;for(a=a.list.iterator();a.hasNext();)d=
a.next(),e=this.list_0,f=this.i_0,d=this.CurrentPosition_0().plus_j8uhfx$(b.times_za3lpa$(d)),e.put_xwzc9p$(f,d),this.i_0=this.i_0+1|0;this.i_0=c}};N.prototype.add_0=function(a){var b=this.i_0;this.i_0=this.i_0-a.leftBy|0;for(a=a.list.iterator();a.hasNext();){var c=a.next(),d=this.list_0,e=this.i_0;c=this.CurrentPosition_0().plus_za3lpa$(c);d.put_xwzc9p$(e,c);this.i_0=this.i_0+1|0}this.i_0=b};N.prototype.CurrentPosition_0=function(){var a=this.list_0,b=this.i_0,c=a.get_11rb$(b);null==c?(c=t(0),a.put_xwzc9p$(b,
c),a=c):a=c;return a};N.$metadata$={kind:J,simpleName:"runProgram",interfaces:[]};var v=G.PromoCompiler||(G.PromoCompiler={});v.BigInt_init_za3lpa$=t;v.BigInt_init_j8uhfx$=U;v.BigInt=f;Object.defineProperty(v,"pass",{get:function(){return ua}});Object.defineProperty(wa,"Companion",{get:Na});v.Promo=wa;v.addCommand_init_za3lpa$=xa;v.addCommand=x;v.addProductsCommand=L;Object.defineProperty(v,"bbcompiler",{get:kb});v.bodyInterface=n;v.callIfCommand=w;v.commandInterface=Z;v.foreverCommand=K;
Object.defineProperty(E,"Companion",{get:za});v.funCommand=E;Object.defineProperty(P,"NotZero",{get:fa});Object.defineProperty(P,"Positive",{get:ja});Object.defineProperty(P,"Negative",{get:ka});v.If=P;v.ifCommand_init_za3lpa$=Ba;v.ifCommand=B;v.inliner=aa;Object.defineProperty(G,"running",{get:function(){return W},set:function(a){W=a}});Object.defineProperty(G,"program",{get:function(){return Fb},set:function(a){Fb=a}});Object.defineProperty(G,"input",{get:pb,set:function(a){Ca=a}});Object.defineProperty(G,
"output",{get:Da,set:function(a){Ea=a}});Object.defineProperty(G,"runButton",{get:oa,set:function(a){Fa=a}});Object.defineProperty(G,"stopButton",{get:pa,set:function(a){Ga=a}});Object.defineProperty(G,"inputx",{get:qa,set:function(a){Ha=a}});Object.defineProperty(G,"output_result",{get:qb,set:function(a){Ia=a}});Object.defineProperty(G,"inited",{get:function(){return Ka},set:function(a){Ka=a}});Object.defineProperty(G,"worker",{get:ra,set:function(a){Ja=a}});G.init=rb;G.toStr=function(){Ka||rb();
Da().value=Na().toBBCL_61zpoe$(pb().value);oa().disabled=!1;pa().disabled=!0;W=!1;var a=S(ca(Da().value,"\n"," "),[" "]).get_za3lpa$(1),b=r(a,"x");if(r(a,"i"))qa().disabled=!0,qa().value="0";else if(b)qa().disabled=!1;else throw m("Syntax Error");};G.run=function(a){if(!1===W){Ja=new Worker("js/worker.js");W=!0;oa().disabled=!0;pa().disabled=!1;a=Da().value;var b=ca(qa().value,String.fromCharCode(Db(0)),"");b=bb(e.isCharSequence(b)?b:z()).toString();ra().postMessage(a+String.fromCharCode(ab(Db(0)))+
b);ra().onmessage=Hb}};G.halt=function(a){!0===W&&(ra().terminate(),W=!1,oa().disabled=!1,pa().disabled=!0)};v.moveCommand=D;v.programCommand_init=db;v.programCommand=H;Object.defineProperty(R,"For",{get:la});Object.defineProperty(R,"While",{get:ia});v.loop=R;v.repeatCommand=F;v.runProgram=N;E.prototype.deep_set_level_za3lpa$=n.prototype.deep_set_level_za3lpa$;E.prototype.get_calls_za3lpa$=n.prototype.get_calls_za3lpa$;E.prototype.read_body_61zpoe$=n.prototype.read_body_61zpoe$;B.prototype.deep_set_level_za3lpa$=
n.prototype.deep_set_level_za3lpa$;B.prototype.get_calls_za3lpa$=n.prototype.get_calls_za3lpa$;B.prototype.read_body_61zpoe$=n.prototype.read_body_61zpoe$;H.prototype.deep_set_level_za3lpa$=n.prototype.deep_set_level_za3lpa$;H.prototype.get_calls_za3lpa$=n.prototype.get_calls_za3lpa$;H.prototype.read_body_61zpoe$=n.prototype.read_body_61zpoe$;F.prototype.deep_set_level_za3lpa$=n.prototype.deep_set_level_za3lpa$;F.prototype.get_calls_za3lpa$=n.prototype.get_calls_za3lpa$;F.prototype.read_body_61zpoe$=
n.prototype.read_body_61zpoe$;var ua=Kb;var Fb=W=null;var Ka=!1;e.defineModule("promo",G);return G}("undefined"===typeof promo?{}:promo,kotlin);
